[package]
name = "demo"
version = "0.1.0"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
starknet = "2.4.0"
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.12.0" }

[[target.starknet-contract]]
sierra = true
casm = true


[tool.sncast.net]
account = "net"
accounts-file = "/home/joy/.starknet_accounts/starknet_open_zeppelin_accounts.json"
url = "https://starknet-goerli.infura.io/v3/470dbcfb303647249fc7f9b6845df562"
